In [4]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
a.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [5]:
b = np.array([1,2,3,4,5])
print(b)
b.shape

[1 2 3 4 5]


(5,)

In [21]:
c = np.random.permutation(4)
print(c)
a[:,c]

[1 2 3 0]


array([[2, 3, 4, 1],
       [6, 7, 8, 5]])

In [28]:
np.linspace(1, 10, 5, endpoint=False)

array([1. , 2.8, 4.6, 6.4, 8.2])